### ISSUE TITLE
图片库去哪里了？

### ISSUE THREAD

**Issue by darknessomi** [zdhxiong/v2ex-material-theme#1]
如题，没有的话真是太不方便了

**Comment by zdhxiong** [comment]
可以暂时试试开发中的新版本，把其他的功能链接都加上了，目前只是无法兼容firefox。
@import url("//dn-startplaytest.qbox.me/v2ex-material-theme/v2ex.min.css");

**Comment by darknessomi** [comment]
Thanks !
