### ISSUE TITLE
css文件不可访问

### ISSUE THREAD

**Issue by gyli** [zdhxiong/v2ex-material-theme#5]
无法访问 plays.b0.upaiyun.com/v2ex-material-theme/v2ex.min.css

v2ex-material-theme2 同样情况

烦请更新地址

**Comment by zdhxiong** [comment]
可以访问的，可能是你的网络问题
你可以在这里测试一下网络：http://pubstatic.b0.upaiyun.com/cdn-health.html

**Comment by gyli** [comment]
看起来是又拍云的原因，我使用AWS美东服务器上的VPN，有一段时间又拍云，包括这个检查页面是不可访问的。

这个 issue 可以关闭了。
